version: "3"
services:
  notebook:
    build: src
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ~/Desktop/datascience_container-main/src:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
